# Generated by Django 4.2.3 on 2023-07-11 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_conta_alter_categoria_valor_planejamento'),
        ('extrato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valores',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.conta'),
        ),
    ]
