# Generated by Django 4.2.3 on 2023-07-11 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contapaga',
            options={'verbose_name_plural': 'Contas Pagas'},
        ),
        migrations.AlterModelOptions(
            name='contapagar',
            options={'verbose_name_plural': 'Contas a Pagar'},
        ),
    ]
